name: WorldGuardGUI
version: ${project.version}
main: me.heymrau.worldguardguiplugin.WorldGuardGUIPlugin
author: HeyMrau, KarmaXT
website: discord.gg/86j4hCbKFF
api-version: 1.13
depend:
  - WorldGuard
  - WorldEdit
commands:
  wggui:
    permission: worldguardgui.admin
    usage: /wggui <region>
    aliases:
      - worldguardgui
      - wgui