name: WorldGuardGUI
version: ${project.version}
main: me.heymrau.worldguardguiplugin.WorldGuardGUIPlugin
author: HeyMrau
api-version: 1.13
depend:
  - WorldGuard
  - WorldEdit
commands:
  wggui:
    permission: worldguardgui.gui
    usage: /wggui <region>
    aliases:
      - worldguardgui
      - wgui