name: WorldGuardGUI
version: ${project.version}
main: me.heymrau.worldguardguiplugin.WorldGuardGUIPlugin
api-version: 1.13
depend:
  - WorldGuard
  - WorldEdit
commands:
  wggui:
    permission: worldguardgui.admin
    aliases:
      - worldguardgui
      - wgui